#!/bin/bash

# Arithmetic expansion

a="10"
b="9990"
c="-50"

# Operator: +
echo "$a + $b = $((a + b))"
# Operator: -
echo "$a - $b = $((a - b))"
# Operator: /  (Ex 1)
echo "$a / $b = $((a / b))"
# Operator: /  (Ex 2)
echo "$b / $a = $((b / a))"
# Operator: *
echo "$b * $a = $((b * a))"
