#!/bin/bash

# Shell options

# Använd set-kommandot

# e avbryter hela skriptet om något kommando misslyckas, utan att
# det hanteras

set -e

echo "rad1"
false || echo "Lite fel"
if false; then
    echo "Lite mer fel"
fi
echo "rad2"
