#!/bin/bash

# Shell options

# Använd set-kommandot

# e avbryter hela skriptet om något kommando misslyckas, utan att
# det hanteras

set -e

for namn in ove britta ulla; do
    echo "namn: $namn"
done
