#!/bin/bash

# trap fångar "signaler" till processen

# Vi använder en temporär fil

touch mintempfil

for ((count = 0; count < 10000; count++)); do
    echo "$RANDOM" >>mintempfil
    sleep 1
done

sort -n tempfil | head
